spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to Loan service related QA APIs"
  contactDetails:
    name: "Rocky Balbo - QA Lead"
    email: "rockybalbo@mail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371