spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to Loan service related production APIs"
  contactDetails:
    name: "John Wick - Product Owner"
    email: "johnwick@mail.com"
  onCallSupport:
    - (453) 357-9510
    - (453) 654-7533
